version: 2
jobs:
  build:
    branches:
      only: master
    docker:
      - image: node:8.9
    steps:
      - checkout
      - run:
          name: Install node modules
          command: npm install
  test:
    steps:
      - run:
          name: Run tests
          command: npm run test
#   deploy:
#     steps:
#       - run:
#           name: Deploy to gh-pages
#           command: npm run deploy
# workflows:
#   version: 2
#   build-test-deploy:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build
#       - deploy:
#           requires:
#             - test