version: 2
jobs:
  build:
    docker:
      - image: node:8.9
    steps:
      - checkout
      - run:
          name: Install node modules
          command: npm install
  test:
    docker:
      - image: node:8.9
    steps:
      - checkout
      - run:
          name: Install node modules
          command: npm install
      - run:
          name: Run tests
          command: npm run test
  deploy:
    docker:
      - image: node:8.9
    steps:
      - checkout
      - run:
          name: Install node modules
          command: npm install
      - run:
          name: Deploy to gh-pages
          command: npm run deploy
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - test:
          requires:
            - build
      # - deploy:
      #     filters:
      #       branches:
      #         only: master
      #     requires:
      #       - test